name: First Workflow

on:
  push:
    branches:
      - main

jobs:
  example-jobs:
    runs-on: ubuntu-latest
  
    steps:
       - name: Print a Welcome Message.
         run: echo "Welcome to our GitHub Actions Workflow!" # I use 'run:.' to run this script on Shell Script 
     
     
